basePath: /
definitions:
  models.Lobby:
    properties:
      changed_at:
        type: string
      created_at:
        type: string
      id:
        type: string
      lobby_url:
        type: string
      user_list:
        items:
          $ref: '#/definitions/models.User'
        type: array
      video_url:
        type: string
    type: object
  models.User:
    properties:
      id:
        type: string
      lobby_id:
        type: string
      name:
        type: string
    type: object
externalDocs:
  description: OpenAPI
host: localhost:8080
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger Shareen
  version: "1.0"
paths:
  /lobby/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Id of lobby
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Lobby'
  /lobby/all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Lobby'
            type: array
  /lobby/create:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Lobby'
  /lobby/delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id for deleting
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
  /lobby/deleteall:
    delete:
      consumes:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
  /lobby/lobbyusers/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: lobby id to get all users there
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
  /lobby/update:
    patch:
      consumes:
      - application/json
      parameters:
      - description: update lobby
        in: body
        name: lobby
        schema:
          $ref: '#/definitions/models.Lobby'
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
  /user/:id:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Id of user
        in: query
        name: userid
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
    get:
      consumes:
      - application/json
      parameters:
      - description: Id of user
        in: query
        name: userid
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Lobby'
  /user/allusers:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Lobby'
            type: array
  /user/create/{name}:
    post:
      consumes:
      - application/json
      parameters:
      - description: name of user
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
  /user/update:
    patch:
      consumes:
      - application/json
      parameters:
      - description: Id of user
        in: query
        name: user
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
