basePath: /
definitions:
  models.Lobby:
    properties:
      id:
        type: integer
      lobbdyURL:
        type: string
      users:
        items:
          $ref: '#/definitions/models.User'
        type: array
      videoURL:
        type: string
    type: object
  models.User:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
  title: Shareen API
  version: "1.0"
paths:
  /lobby/:
    post:
      description: Create lobby | ПОТОМ НУЖНО ПОЛУЧАТЬ ID ПОЛЬЗОВАТЕЛЯ, КОТОРЫЙ СОЗДАЕТ
        ЛОББИ
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create lobby
      tags:
      - Lobby
  /lobby/{url}:
    delete:
      description: Delete lobby by unique url
      parameters:
      - description: delete lobby by unique url
        in: path
        name: url
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete lobby
      tags:
      - Lobby
    get:
      description: Get lobby by unique url
      parameters:
      - description: lobby search by url
        in: path
        name: url
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Lobby'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get lobby
      tags:
      - Lobby
  /lobby/{url}-{video}:
    patch:
      description: Update vieo URL in lobby
      parameters:
      - description: update video URL in lobby by unique url
        in: path
        name: url
        type: string
      - description: update video URL in lobby by unique url
        in: path
        name: video
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update vieo URL in lobby
      tags:
      - Lobby
  /user/{id}:
    delete:
      description: Delete user by id
      parameters:
      - description: Delete user by ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete user
      tags:
      - User
    get:
      description: Get user by user id
      parameters:
      - description: get user by id
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get user
      tags:
      - User
  /user/{name}:
    post:
      description: Create user
      parameters:
      - description: Create user using his name
        in: path
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create user
      tags:
      - User
  /user/{url}-{id}:
    patch:
      description: Join user in lobby by userID, lobbyID
      parameters:
      - description: Join user in lobby by unique url
        in: path
        name: url
        type: string
      - description: Join user in lobby by unique url
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Join user
      tags:
      - User
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
