definitions:
  models.Lobby:
    properties:
      changed_at:
        type: string
      created_at:
        type: string
      id:
        type: string
      lobby_url:
        type: string
      user_list:
        items:
          $ref: '#/definitions/models.User'
        type: array
      video_url:
        type: string
    type: object
  models.LobbyUser:
    properties:
      lobby_id:
        type: string
      user_id:
        type: string
    type: object
  models.User:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  models.VideoLobby:
    properties:
      lobby_id:
        type: string
      video_url:
        type: string
    type: object
info:
  contact: {}
paths:
  /lobby/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Id of lobby
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Lobby'
      tags:
      - lobbies
  /lobby/all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Lobby'
            type: array
      tags:
      - lobbies
  /lobby/create:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Lobby'
      tags:
      - lobbies
  /lobby/delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id for deleting
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
      tags:
      - lobbies
  /lobby/lobbyusers/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: lobby id to get all users there
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      tags:
      - lobbies
  /lobby/seturl:
    post:
      consumes:
      - application/json
      parameters:
      - description: videoUrl and lobbyId to set videoUrl in lobby
        in: body
        name: videoUrlLobbyId
        required: true
        schema:
          $ref: '#/definitions/models.VideoLobby'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      tags:
      - lobbies
  /lobby/update:
    patch:
      consumes:
      - application/json
      parameters:
      - description: update lobby
        in: body
        name: lobby
        schema:
          $ref: '#/definitions/models.Lobby'
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
      tags:
      - lobbies
  /user/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Id of user
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - users
    get:
      consumes:
      - application/json
      parameters:
      - description: Id of user
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      tags:
      - users
  /user/allusers:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      tags:
      - users
  /user/create/{name}:
    post:
      consumes:
      - application/json
      parameters:
      - description: name of user
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      tags:
      - users
  /user/join:
    post:
      consumes:
      - application/json
      parameters:
      - description: Id of lobby and user
        in: body
        name: user
        schema:
          $ref: '#/definitions/models.LobbyUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      tags:
      - users
  /user/update:
    patch:
      consumes:
      - application/json
      parameters:
      - description: Id of user
        in: body
        name: user
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - users
swagger: "2.0"
